name: building the module for SWI Prolog

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install SWI Prolog
      run: sudo apt-get -y install swi-prolog-nox
    - name: autoconf
      run: aclocal --force && autoheader --force && autoconf --force
    - name: configure
      run: ./configure
    - name: make swi
      run: make swi
    - name: installation
      run: |
        mkdir -v -p ${HOME}/lib/sbcl
        cp -v predidx-Linux ${HOME}/lib/sbcl/predidx
        cp -v src/predidx.qlf ${HOME}/lib/sbcl/
        echo ":- assertz(file_search_path(sbcl,'${HOME}/lib/sbcl'))." >> ${HOME}/.swiplrc
    - name: make check
      run: make check
