name: building the module for SWI Prolog

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install SWI Prolog
      run: sudo apt-get -y install swi-prolog-nox
    - name: configure
      run: ./configure
    - name: make swi
      run: make swi
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
